### PR TITLE
Add imputed notebook

### PR DESCRIPTION
**Pull request by morriscb**
Add example for imputed data.

Merge after data is added to ABC Atlas.

### CODE REVIEW

**Comment by lydiang** [comment]
@morriscb  - I drafted some intro section of the notebook and description markdown - let's start with these. Please fix language issues as you see fit.

Here is a draft intro section for the impute notebook

**MERFISH whole brain spatial transcriptomics cells with imputed genes**

In the MERFISH tutorial (part 1), we discussed how each set form the MERFISH data was mapped to the whole mouse brain taxonomy using a hierarchical correlation method.  To further integrate the transcriptomics and spatial profiles of each cell type, 10Xv3 expression was projected or imputed into the MERFISH space. The basic idea is to compute the k-nearest neighbors (KNNs) among the 10Xv3 cells for each MERFISH cell and use the average expression of these neighbors for each gene as the impute values. Further details can be found in the methods section of [Yao et. al](https://doi.org/10.1038/s41586-023-06812-z).

In this notebook, we will show the basics on how to access the imputed gene data and perform some illustrative comparison between expression 10X, MERFISH measured and impute expression similar to [Extended Data Fig 8](https://www.nature.com/articles/s41586-023-06812-z/figures/14) in the manuscript.

-------------------------------------
And draft intro for the data description markdown file

**Imputed MERFISH spatial transcriptomics of a single adult mouse brain**

The MERFISH spatial transcriptomics dataset  ([MERFISH-C57BL6J-638850](https://github.com/AllenInstitute/abc_atlas_access/blob/u/morriscb/addImputedNotebook/descriptions/MERFISH-C57BL6J-638850.md)) was mapped to the whole mouse brain taxonomy ([WMB-taxonomy](https://github.com/AllenInstitute/abc_atlas_access/blob/u/morriscb/addImputedNotebook/descriptions/WMB-taxonomy.md)) using a hierarchical correlation method. To further integrate the transcriptomics and spatial profiles of each cell type, 10Xv3 expression was projected or imputed into the MERFISH space. The basic idea is to compute the k-nearest neighbors (KNNs) among the 10Xv3 cells for each MERFISH cell and use the average expression of these neighbors for each gene as the impute values. Further details can be found in the methods section of [Yao et. al](https://doi.org/10.1038/s41586-023-06812-z).

**Comment by lydiang** [comment]
@morriscb - feedback on the notebook

- In the intro - add hyperlink to "Yao et al" and "Extended Data Fig 8"
- The group by "neurotransmitter" isn't very informative for these 3 genes. Let's drop and change text

In this example, we create a dataframe comprising of expression of the our 3 selected genes for all the cells in the dataset. We can group the cells by various different metadata. For example, grouping expression by dissection region of interest shows that each of these genes have distinct spatial patterns. The MERFISH data allows us to visualize these patterns in anatomical context.

- In section "Comparison of imputed genes to measured genes across the brain"

Change text from : 
"In this next section, we will look at the overlap of our selected genes with the C57BL6J MERSHFISH dataset."

To: 
"In this next section, perform some illustrative comparison between MERFISH measured and impute expression similar to Extended Data Fig 8 in the manuscript."

(Please add hyperlink to figure)

- In the comparision, let's show the section side-by-side first before the correlation plot. Can you repeat for section "C57BL6J-638850.40" and "C57BL6J-638850.14"?

- Subheading for section side-by-side: "Measured vs imputed MERFISH expression (spatial view)"
- Subheading for correlation plot" "Measured vs impute MERFISH expression (cluster level correlation)"

**Comment by lydiang** [comment]
For data description file

- Please add hyperlinik to Yao et al and (MERFISH-C57BL6J-638850) and (WMB-taxonomy)

**Comment by morriscb** [comment]
Updated the files as requested. Take a look to see if you like the changes.

**Comment by lydiang** [comment]
More minor text edits for imputed notebook

- deleted repeated line "MERFISH whole brain spatial transcriptomics cells with imputed genes"
-  discussed how each **set** form the MERFISH data  -> discussed how each cell from the MERFISH data
- **"Expression our selected, imputed genes for the full brain."** -> "Visualize imputed gene expression for selected genes"
- "For example, grouping expression by **dissection region of interest**  -> "For example, grouping expression by brain sections"

In the description markdown file, the "Current Versions" links does not go to the right location in S3

**Pull request merged**
